# Generated by Django 3.2 on 2021-05-07 11:02

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('about', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=50)),
                ('github', models.CharField(blank=True, max_length=50, null=True)),
                ('uni', models.CharField(max_length=100)),
                ('uni_subject', models.CharField(max_length=50)),
                ('uni_result', models.CharField(max_length=10)),
                ('uni_passing', models.CharField(blank=True, max_length=4, null=True)),
                ('clg', models.CharField(max_length=100)),
                ('clg_group', models.CharField(max_length=10)),
                ('clg_result', models.CharField(max_length=10)),
                ('clg_passing', models.CharField(max_length=4)),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('C', 'C'), ('C++', 'C++'), ('PHP', 'PHP'), ('Python', 'Python'), ('Java', 'CJava'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('JavaScript', 'JavaScript'), ('MySql', 'MySql'), ('Oracle', 'Oracle'), ('Postgres', 'Postgres'), ('MongoDB', 'MongoDB'), ('CodeIgniter', 'CodeIgniter'), ('Django', 'Django'), ('Flask', 'Flask'), ('ASP.Net', 'ASP.Net'), ('Android', 'Android'), ('UI/UX', 'UI/UX'), ('Android', 'Android'), ('Photoshop', 'Photoshop'), ('Premiere pro', 'Premiere pro'), ('Drawing', 'Drawing'), ('MS Office', 'MS Office'), ('XCEL', 'XCEL'), ('PowerPoint', 'PowerPoint'), ('Linux', 'Linux'), ('AWS', 'AWS'), ('CCNA', 'CCNA')], max_length=203)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('seeking', models.CharField(blank=True, max_length=100, null=True)),
                ('theme', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
