# Generated by Django 3.2 on 2021-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolioupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioupdate',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='media/images'),
        ),
    ]
