# Generated by Django 3.2 on 2021-05-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_portfolioupdate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioupdate',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
    ]
