# Generated by Django 3.2 on 2021-05-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210509_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioupdate',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioupdate',
            name='theme',
            field=models.CharField(blank=True, default='default', max_length=50, null=True),
        ),
    ]
