# Generated by Django 3.2 on 2021-05-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210509_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioupdate',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
