# Generated by Django 3.2 on 2021-05-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210509_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioupdate',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='portfolioupdate',
            name='theme',
            field=models.CharField(default='default', max_length=50, null=True),
        ),
    ]
