# Generated by Django 3.2 on 2021-05-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210509_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioupdate',
            name='theme',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
