# Generated by Django 3.2 on 2021-05-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_portfoliotheme_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skicon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
