# Generated by Django 3.2 on 2021-05-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
