# Generated by Django 3.2 on 2021-05-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_portfoliotheme_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioupdate',
            name='skills',
        ),
        migrations.AddField(
            model_name='portfolioupdate',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='core.Skill'),
        ),
    ]
