# Generated by Django 3.2 on 2021-05-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210510_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioupdate',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.Skill'),
        ),
    ]
