# Generated by Django 3.2 on 2021-05-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_portfolioupdate_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioupdate',
            name='skills',
        ),
        migrations.AddField(
            model_name='portfolioupdate',
            name='skills',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
