# Generated by Django 3.2 on 2021-05-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210510_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioupdate',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/user'),
        ),
    ]
