# Generated by Django 3.2 on 2021-05-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210511_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioupdate',
            old_name='company',
            new_name='company1',
        ),
        migrations.RenameField(
            model_name='portfolioupdate',
            old_name='designation',
            new_name='company2',
        ),
        migrations.RenameField(
            model_name='portfolioupdate',
            old_name='period',
            new_name='period1',
        ),
        migrations.AddField(
            model_name='portfolioupdate',
            name='designation1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioupdate',
            name='designation2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='portfolioupdate',
            name='period2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
