# Generated by Django 3.2 on 2021-05-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_portfolioupdate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioupdate',
            name='popularity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
